name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Login to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel login --token $VERCEL_TOKEN

    - name: Set Vercel environment variables
      env:
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "$DB_PORT" | vercel env add DB_PORT production
        echo "$DB_HOST" | vercel env add DB_HOST production
        echo "$DB_NAME" | vercel env add DB_NAME production
        echo "$DB_USER" | vercel env add DB_USER production
        echo "$DB_PASSWORD" | vercel env add DB_PASSWORD production

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel --prod --token $VERCEL_TOKEN
